baseURL = 'https://rentfbtrailer.com'
languageCode = 'en-us'
title = 'Rent Trailers in Flowery Branch'
theme = 'hugo-universal-theme'

[params]
    disabled_logo = false
    logo = 'content/img/logo.png'
    logo_text = 'Flowery Branch Trailer Rental'