baseURL = 'https://rentfbtrailer.com'
languageCode = 'en-us'
title = 'Rent Trailer in Flowery Branch, GA | Dump Trailers, Utility Trailers, Car Haulers'
theme = 'hugo-universal-theme'

[params]
    logo = 'img/logo.png'
    logo_text = 'Flowery Branch Trailer Rental'
    dropdown_mouse_over = true

[params.widgets]
    search = true
    categories = true
    tags = true

[params.topbar]
    enable = true
    text = "<p>Contact us at (470) 645-1899 or hello@rentfbtrailer.com.</p>"

[[menu.topbar]]
    weight = 2
    name = "GitHub"
    url = "https://github.com/jwilliamshirley"
    pre = "<i class='fas fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 1
    name = "Facebook"
    url = "https://www.facebook.com/profile.php?id=61573847370055"
    pre = "<i class='fas fa-2x fa-facebook'></i>"

[[menu.main]]
    name       = "Menu"
    identifier = "menu.main"
    url        = "/"
    weight     = 1
[[menu.main]]
    name       = "Renter Login"
    url        = "/docklyne"
    weight     = 1
    parent     = "menu.main"
[[menu.main]]
    name       = "About"
    url        = "/about"
    weight     = 2
    parent     = "menu.main"
[[menu.main]]
    name       = "Contact Us"
    url        = "/contact"
    weight     = 4
    parent     = "menu.main"
[[menu.main]]
    name       = "FAQ"
    url        = "/faq"
    weight     = 3
    parent     = "menu.main"